forum/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'welcome/index'
 
  resources :questions do
    resources :answers
  end
 
  root 'welcome#index'
end

forum/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud
    if user.present?
      can :read, :all
      can :crud, Question, user_id: user.id
      can :create, Answer, :all
      can :destroy, Answer, user_id: user.id
      #return unless user && user.admin?
       # can :access, :rails_admin 
        #can :read, :dashboard
    end
  end
end

forum/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true
end

forum/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

forum/app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
    belongs_to :user
    validates :assunto, presence: true,
    length: { minimum: 2 }
end

forum/app/models/user.rb
class User < ApplicationRecord
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

forum/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
  end
  
  def create
    @user = current_user
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    if @answer.save!
      redirect_to question_path(@question)
    else
      render 'new'
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question)
  end
    
  private
    def answer_params
      params.require(:answer).permit(:body, @current_user_id)
    end
end

forum/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    def set_current_user
        User.current = current_user
    end
end

forum/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @questions = Question.all
    end
    
    def show
        @question = Question.find(params[:id])
    end
    
    def new
        @question = Question.new
    end

    def edit
        @question = Question.find(params[:id])
    end
   
    def create
        @user = current_user
        @question = @user.questions.new(question_params)
 
        if @question.save!
          redirect_to @question
        else
          render 'new'
        end
    end

    def update
        @question = Question.find(params[:id])
       
        if @question.update(question_params)
          redirect_to @question
        else
          render 'edit'
        end
    end

    def destroy
        @question = Question.find(params[:id])
        @question.destroy
        
        redirect_to questions_path
    end

    private
        def question_params
            params.require(:question).permit(:assunto, :pergunta, current_user)
        end
end

forum/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

forum/app/helpers/answers_helper.rb
module AnswersHelper
end

forum/app/helpers/application_helper.rb
module ApplicationHelper
end

forum/app/helpers/questions_helper.rb
module QuestionsHelper
end

forum/app/helpers/welcome_helper.rb
module WelcomeHelper
end

forum/app/views/answers/_answer.html.erb
<p>
  <strong>Usuário:</strong>
  <%= answer.user_id %>
</p>
 
<p>
  <strong>Resposta:</strong>
  <%= answer.body %>
</p>
 
<p>
  <%= link_to 'Deletar Comentário', [answer.question, answer],
               method: :delete,
               data: { confirm: 'Tem certeza que deseja deletar?' } %>
</p>

forum/app/views/answers/_form.html.erb
<%= form_with(model: [ @question, @question.answers.build ], local: true) do |form| %>
  <p>
    <%= form.label :name, 'Escreva sua resposta:' %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

forum/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logado como: <strong><%= current_user.email %></strong>.
      <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

forum/app/views/questions/_form.html.erb
<%= form_with model: @question, local: true do |form| %>
 
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :assunto %><br>
    <%= form.text_field :assunto %>
  </p>
 
  <p>
    <%= form.label :pergunta %><br>
    <%= form.text_area :pergunta %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

forum/app/views/questions/edit.html.erb
<h1>Editar Pergunta</h1>
 
<%= render 'form' %>
 
<%= link_to 'Voltar', questions_path %>

forum/app/views/questions/index.html.erb
<h1>Perguntas</h1>
 
<table>
  <tr>
    <th>Assunto</th>
    <th>Pergunta</th>
    <th colspan="3"></th>
  </tr>
 
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.assunto %></td>
      <td><%= question.pergunta %></td>
      <td><%= link_to 'Mostrar', question_path(question) %></td>
      <td><%= link_to 'Editar', edit_question_path(question) %></td>
      <td><%= link_to 'Deletar', question_path(question),
        method: :delete,
        data: { confirm: 'Tem certeza que deseja deletar?' } %></td>
    </tr>
  <% end %>
  
  <%= link_to 'Nova Pergunta', new_question_path %>
</table>

forum/app/views/questions/new.html.erb
<h1>Faça uma pergunta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', questions_path %>

forum/app/views/questions/show.html.erb
<p>
  <strong>Assunto:</strong>
  <%= @question.assunto %>
</p>
 
<p>
  <strong>Pergunta:</strong>
  <%= @question.pergunta %>
</p>

<p>
  Autor:
  <%= @question.user_id %>
</p>

<h2>Respostas</h2>
<%= render @question.answers %>

<h4>Responder:</h4>
<%= render 'answers/form' %>

<%= link_to 'Editar', edit_question_path(@question) %> |
<%= link_to 'Voltar', questions_path %>

forum/app/views/welcome/index.html.erb
<h1>Coop</h1>
<h3>Ambiente de cooperação entre alunos da FGA<br>
com o objetivo de sanar dúvidas.</h3>

<%= link_to 'Ir para o fórum', controller: 'questions' %>